spring:
  application:
    name: Import_export_CSV
  datasource:
    url: jdbc:mysql://localhost:3306/database_managager
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
