spring:
  application:
    name: Import_export_CSV
  datasource:
    url: jdbc:mysql://localhost:3306/database_managager
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  messages:
    basename: i18n/messages
    encoding: UTF-8 # Ensure the correct encoding for the message properties

  i18n:
    enabled: true

  # Add this section for dynamic locale switching
#  web:
#    locale: vi_VN # Default locale is Vietnamese
#    locale-resolver: session # Allow session-based locale switching

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true